title: My DevCat Studios Portfolio

description: This is my portfolio showcasing my projects and skills.

baseurl: "" # leave empty since this is your user page

url: "https://zamora105.github.io" # replace YOURUSERNAME with your GitHub username

theme: jekyll-theme-merlot # replace “merlot” with your chosen theme from the list
